### ISSUE TITLE
Crash when query string contains &&

### ISSUE THREAD

**Issue by dominicfreeston** [lostisland/hurley#11]
[Line 45 in query.rb](https://github.com/lostisland/hurley/blob/master/lib/hurley/query.rb#L45) causes a crash if `pair` is `nil`, which can happen in the (possibly invalid but seen in the wild) case where the query string contains &&.

```ruby
def parse_query(raw_query)
    raw_query.to_s.split(AMP).each do |pair|
        escaped_key, escaped_value = pair.split(EQ, 2)
        key = CGI.unescape(escaped_key)
        value = escaped_value ? CGI.unescape(escaped_value) : nil
        send(:decode_pair, key, value)
    end
end
```

Could easily fix by simply wrapping the block in `if pair != nil`, but maybe there's a nicer ruby-like to do it (still pretty new to it)?

For future reference, would an immediate pull-request be preferred to raising an issue like this?

**Comment by technoweenie** [comment]
Thanks for the report.  Issues are fine, but a PR demonstrating the bug is even better.  A PR with a tested fix gets you a gold star!
