### ISSUE TITLE
Mutex in hurley.rb

### ISSUE THREAD

**Issue by rusikf** [lostisland/hurley#13]
Why in hurley.rb this code needed?
```ruby
MUTEX = Mutex.new
```
```ruby
  def self.default_client
    @default_client ||= mutex { Client.new }
  end
```
It looks, that in hurley repository there is no code with threads, which share same data, which must be locked.

**Comment by technoweenie** [comment]
This makes the method safe for threaded apps that use hurley.  They should be able to depend on something like `Hurley.default_client`.

**Comment by eric** [comment]
Shouldn't that mutex be outside the assignment?

You're still going to have issues with multiple threads possibly trying to assign at the same time.

**Comment by technoweenie** [comment]
Blah, yes.

**Comment by technoweenie** [comment]
https://github.com/lostisland/hurley/commit/a66d2c151c1f15a10b259872d48a683c102d08d1
