### ISSUE TITLE
Issue Getting Basic Auth to Work

### ISSUE THREAD

**Issue by kkirsche** [lostisland/hurley#16]
Hey guys,

So I'm trying to use Hurley and I have to work with one API endpoint which uses HTTP Basic Auth. It keeps giving me access denied via Hurley but if I copy / paste the URL I generate with the `https://username:password@website.com/api/end/point.json`

```ruby
response = @client.get("https://#{username}:#{password}@rubygems.org/api/v1/api_key.#{format}")

puts response.status_code
puts response.body
```

and I'm getting:

```shell
401
HTTP Basic: Access denied.

```

Pasting the result of `"https://#{username}:#{password}@rubygems.org/api/v1/api_key.#{format}"` works though.

**Comment by kkirsche** [comment]
Oddly was fixed with:

```ruby
response = @client.get("https://#{username}:#{password}@rubygems.org/api/v1/api_key.#{format}") do |req|
            req.header[:Authorization] = req.url.basic_auth.gsub!(/(\n|\r|\t)+/, '')
          end
```

Apparently it introduced newlines into the Auth header.

**Comment by technoweenie** [comment]
That's not a fix, that's a workaround :)  Thanks for filing this!

**Comment by kkirsche** [comment]
@technoweenie 

I believe I may have identified what is causing this issue, though I'd want someone else to check to make sure.

I believe this issue has to do with the use of `Base64.encode64()`. For example, let's say for example that we have the following hardcoded strong password which a user generated online or with a password manager: 
```ruby
# base.rb

require 'base64'
puts Base64.encode64("rT1eRQPOrQWV4Ye^1{rA23gJy;Rtjr]PZ#bXjhhjFBQUNF").rstrip

```

When encoded in Base64, this results in:
```shell
clQxZVJRUE9yUVdWNFllXjF7ckEyM2dKeTtSdGpyXVBaI2JYamhoakZCUVVO
Rg==
```

For this reason, a gsub is necessary.

**Comment by kkirsche** [comment]
Patch submitted :smiley:

**Comment by technoweenie** [comment]
@kkirsche Thanks!  I commented on the PR.
