### ISSUE TITLE
Best approach for testing adapter gems

### ISSUE THREAD

**Issue by Ben-M** [lostisland/hurley#2]
Do you have any thoughts about the best way for Hurley adapter gems to run integration tests?

It's really nice that Hurley::Test::Integration has moved into the lib directory (which saves nastiness like this):
```
faraday_gem_location = Gem.loaded_specs['faraday'].gem_dir
integration_location = File.join(faraday_gem_location, 'test', 'adapters', 'integration')
require integration_location
```

However, what's the best way for the gems to spin up the server and trigger the tests? This probably works but is ugly:

adapter-gem/script/test:
```
#!/usr/bin/env bash
hurley_path=`bundle show hurley_path`
$hurley_path/script/test $@
```

adapter-gem/script/server:
```
#!/usr/bin/env bash
hurley_path_path=`bundle show hurley_path`
$hurley_path_path/script/server $@
```

**Comment by technoweenie** [comment]
What about using rake?  `script/test` can just be updated to use commands like `rake hurley:start_server`.  Adapter libraries can just require `hurley/tasks` into their rake file to do the same thing.

**Comment by Ben-M** [comment]
That sounds like a good direction. 

Let me know if you plan to look at it, if not then I may get the chance on Sunday.

**Comment by technoweenie** [comment]
Got it working: https://github.com/lostisland/hurley-excon

The `script/test` still has a lot of copy pasta, but at least it's not copying test content.  Would be cool to wrap that up too though.
