### ISSUE TITLE
Hurley.default not being respected

### ISSUE THREAD

**Issue by cemeyer2** [lostisland/hurley#23]
The README says that one can:

```ruby
# Change it globally.
Hurley.default = Hurley::Query::Flat
```

Although this is not implemented (or has been removed). In order to globally change it, I had to monkey patch:

```ruby
module Hurley
  class Query
    def self.default
      @default ||= Flat
    end
  end
end
```

**Comment by technoweenie** [comment]
Fixed in f47cc9fd008f98f8597bb3e16acfa15c86b115d7. Though if I was smart I would've done this before shipping v0.2 :)
