### ISSUE TITLE
simple query building unclear

### ISSUE THREAD

**Issue by semdinsp** [lostisland/hurley#24]
query = { time: Time.now, fred: "hello")
In httpclient i used to be able to do httpclient.get(uri,query).  This worked nicely.

In Hurley i tried the following:
c=Hurley::Cleint.new  url="https://datadrop.wolframcloud.com/api/v1.0/Add?"
c.get(Hurley::Query::Flat.new(query))

this comes close to working but strips the ? from the url.

Eventually i had to do the following:

  q="https://datadrop.wolframcloud.com/api/v1.0/Add?"+ Hurley::Query::Flat.new(qdata).to_s
          res=Hurley.get(q)
this does not seem to in keeping with the style of Hurley... Any suggestions for improving the handling of my hash structured query or keeping the question mark in the url?

**Comment by technoweenie** [comment]
```ruby
c = Hurley::Client.new "https://datadrop.wolframcloud.com/api/v1.0/Add"
c.get nil, :time => Time.now.iso8601, :fred => "hello"
# #<Hurley::Response GET https://datadrop.wolframcloud.com/api/v1.0/Add?time=2015-09-05T10%3A04%3A46-06%3A00&fred=hello == 400 (51 bytes) 822ms>
```

The "Hurley way" would be to create a single client for your application:

```ruby
c = Hurley::Client.new "https://datadrop.wolframcloud.com/api/v1.0"
c.get "Add", :time => Time.now.iso8601, :fred => "hello"
# #<Hurley::Response GET https://datadrop.wolframcloud.com/api/v1.0/Add?time=2015-09-05T10%3A06%3A46-06%3A00&fred=hello == 400 (51 bytes) 638ms>
```

Notice how the `#get` call adds the "Add" path to the end of the base path given to `Hurley::Client.new`.
